# Generated by Django 5.0.1 on 2024-02-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shows',
            new_name='show',
        ),
    ]
