# Generated by Django 5.0.1 on 2024-02-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_shows_show'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cinema',
            new_name='cinema_item',
        ),
        migrations.RenameModel(
            old_name='images',
            new_name='image',
        ),
    ]
