# Generated by Django 5.0.1 on 2024-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_trending_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
