# Generated by Django 5.0.1 on 2024-02-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_date_alter_show_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='date',
            new_name='year',
        ),
    ]
