# Generated by Django 5.0.1 on 2024-02-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_cinema_item_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema_item',
            name='show_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=100),
        ),
    ]
